name: 04.publish.artifacts

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

env:
  buildConfiguration: 'Release'

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v4

      - name: .NET Restore
        run: dotnet restore src/*.sln

      - name: .NET Publish
        run: dotnet publish src/SimpleWeb/SimpleWeb.csp --configuration ${{ env.buildConfiguration }} --output ${{ github.workspace }}/publish

      - name: Upload Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: drop
          path: ${{ github.workspace }}/publish

  deploy:
    needs: build
    if: success()
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: drop

  notify:
    needs: deploy
    if: always()
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Notify
        run: echo "Deployment executed! State- ${{ job.status }}"