name: Demo Build

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  repository_dispatch:
    types: [build]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@v2
      name: Checkout code
    
    - uses: actions/setup-dotnet@v4
      name: Setup .NET
      with:
        dotnet-version: '10.0.x'

    - run: dotnet restore src/*.sln
      name: Restore dependencies

    - name: Build solution
      run: dotnet build src/*.sln --configuration Release --no-restore

    - run: |
        dotnet test src/SimpleWeb.UnitTest/SimpleWeb.UnitTest.csproj --configuration Release --no-restore --no-build --verbosity normal

        echo Hello, world!
      name: Run tests