name: Demo

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

env:
  buildConfig: Debug


jobs:
  cmd1:
    name: Build and Test
    runs-on: ubuntu-24.04-arm

    env:
      buildConfig: Release

    steps:
    - name: CMD
      run: |
        echo ${{ env.DemoEnv }}
        echo ${{ env.buildConfig }}
        echo ${{ vars.DemoVar }}
        echo ${{ secrets.DemoPassword}}

  cmd2:
    name: Build and Test
    runs-on: ubuntu-24.04-arm
    environment: prod

    env:
      buildConfig: Release

    steps:
    - name: CMD
      run: |
        echo ${{ env.DemoEnv }}
        echo ${{ env.buildConfig }}
        echo ${{ vars.DemoVar }}
        echo ${{ secrets.DemoPassword}}
    