name: Test matrix
on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [24]
    steps:
      - uses: ./.github/actions/demo-action
        with:
          date: '0318'
          node-version: ${{ matrix.node }}
          
      - name: Output node version
        run: node --version
